import * as C from '../../constants';

// JSON data for all models: where to load their geometry and what their material is.
// @g: geometry path.
// @m: material color.
// @cs: castShadow.
// @rs: receiveShadow. 
// Note: to save storage space, the data is as concise as possible.
module.exports = {
  models: [
    // Chessboard.
    {
      g: './models/chessboard.json',
      m: C.CHESSBOARD_COLOR,
      cs: false,
      rs: true,
      t: './models/chessboard-texture.png',
    },

    // Whites.
    {
      g: './models/rook.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: 21,
    },
    {
      g: './models/rook.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: -21,
    },
    {
      g: './models/knight.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: 15,
      ry: 160,
    },
    {
      g: './models/knight.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: -15,
      ry: -160,
    },
    {
      g: './models/bishop.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: 9,
    },
    {
      g: './models/bishop.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: -9,
    },
    {
      g: './models/king.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: -3,
    },
    {
      g: './models/queen.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -21,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: 21,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: 15,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: 9,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: -3,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: -9,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: -15,
    },
    {
      g: './models/pawn.json',
      m: C.WHITE_PIECE_COLOR,
      cs: true,
      rs: false,
      x: -15,
      z: -21,
    },

    // Blacks.
    {
      g: './models/rook.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: 21,
    },
    {
      g: './models/rook.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: -21,
    },
    {
      g: './models/knight.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: 15,
      ry: 0,
    },
    {
      g: './models/knight.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: -15,
      ry: 50,
    },
    {
      g: './models/bishop.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: 9,
    },
    {
      g: './models/bishop.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: -9,
    },
    {
      g: './models/king.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: -3,
    },
    {
      g: './models/queen.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 21,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: 21,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: 15,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: 9,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: -3,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: -9,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: -15,
    },
    {
      g: './models/pawn.json',
      m: C.BLACK_PIECE_COLOR,
      cs: true,
      rs: false,
      x: 15,
      z: -21,
    },
  ],
};
