// JSON data for all models: where to load their geometry and what their material is.
// @g: geometry path.
// @m: material color.
// @cs: castShadow.
// @rs: receiveShadow. 
// Note: to save storage space, the data is as concise as possible.
module.exports = {
  models: [
    {
      g: './models/chessboard.json',
      m: 0x0000FF,
      cs: false,
      rs: true,
    },

    // Whites.
    {
      g: './models/rook.json',
      m: 0xFF7F00,
      cs: false,
      rs: false,
      x: -21,
      z: 21,
    },
    {
      g: './models/rook.json',
      m: 0xFF7F00,
      cs: false,
      rs: false,
      x: -21,
      z: -21,
    },
    {
      g: './models/knight.json',
      m: 0xFFFF00,
      cs: true,
      rs: true,
      x: -21,
      z: 15,
      ry: 160,
    },
    {
      g: './models/knight.json',
      m: 0xFFFF00,
      cs: true,
      rs: true,
      x: -21,
      z: -15,
      ry: -160,
    },
    {
      g: './models/bishop.json',
      m: 0x00FF00,
      cs: true,
      rs: true,
      x: -21,
      z: 9,
    },
    {
      g: './models/bishop.json',
      m: 0x00FF00,
      cs: true,
      rs: true,
      x: -21,
      z: -9,
    },
    {
      g: './models/king.json',
      m: 0x4B0082,
      cs: true,
      rs: true,
      x: -21,
      z: -3,
    },
    {
      g: './models/queen.json',
      m: 0x9400D3,
      cs: true,
      rs: true,
      x: -21,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: 21,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: 15,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: 9,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: -3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: -9,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: -15,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: -15,
      z: -21,
    },

    // Blacks.
    {
      g: './models/rook.json',
      m: 0xFF7F00,
      cs: false,
      rs: false,
      x: 21,
      z: 21,
    },
    {
      g: './models/rook.json',
      m: 0xFF7F00,
      cs: false,
      rs: false,
      x: 21,
      z: -21,
    },
    {
      g: './models/knight.json',
      m: 0xFFFF00,
      cs: true,
      rs: true,
      x: 21,
      z: 15,
      ry: 0,
    },
    {
      g: './models/knight.json',
      m: 0xFFFF00,
      cs: true,
      rs: true,
      x: 21,
      z: -15,
      ry: 50,
    },
    {
      g: './models/bishop.json',
      m: 0x00FF00,
      cs: true,
      rs: true,
      x: 21,
      z: 9,
    },
    {
      g: './models/bishop.json',
      m: 0x00FF00,
      cs: true,
      rs: true,
      x: 21,
      z: -9,
    },
    {
      g: './models/king.json',
      m: 0x4B0082,
      cs: true,
      rs: true,
      x: 21,
      z: -3,
    },
    {
      g: './models/queen.json',
      m: 0x9400D3,
      cs: true,
      rs: true,
      x: 21,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: 21,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: 15,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: 9,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: 3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: -3,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: -9,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: -15,
    },
    {
      g: './models/pawn.json',
      m: 0xFF0000,
      cs: true,
      rs: true,
      x: 15,
      z: -21,
    },
  ],
};
